version: '3.8'

services:
  sushi:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./master:/app
      - bundle:/app/vendor/bundle
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - BUNDLE_PATH=/app/vendor/bundle
    entrypoint: ["entrypoint.sh"]
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]

volumes:
  bundle: 

