#!/usr/bin/env ruby
# encoding: utf-8

require 'sushi_fabric'
require_relative 'global_variables'
include GlobalVariables

class FastqcApp <  SushiFabric::SushiApp
  def initialize
    super
    @name = 'Fastqc'
    @params['process_mode'] = 'DATASET'
    @analysis_category = 'QC'
    @description =<<-EOS
A quality control tool for NGS reads<br/>
<a href='http://www.bioinformatics.babraham.ac.uk/projects/fastqc'/>Web-site with docu and a tutorial video</a>
EOS
    @required_columns = ['Name','Read1']
    @required_params = ['paired', 'showNativeReports']
    @params['cores'] = [8, 1, 2, 4, 8]
    @params['cores', "context"] = "slurm"
    @params['ram'] = [15, 30, 62]
    @params['ram', 'description'] = "GB"
    @params['ram', "context"] = "slurm"
    @params['scratch'] = [100, 10, 50, 100]
    @params['scratch', 'description'] = "GB"
    @params['scratch', "context"] = "slurm"
    @params['paired'] = false
    @params['paired', "context"] = "Fastqc"
    @params['showNativeReports'] = false
    @params['showNativeReports', 'description'] = "uses the multi qc summary as primary report; native reports are generated and can be downloaded"
    @params['showNativeReports', "context"] = "Fastqc"
#    @params['libQuantPlots'] = true
#    @params['libQuantPlots', 'description'] = "make plot comparing library quantifications with read numbers"
    @params['specialOptions'] = ''
    @params['cmdOptions'] = ""
    @params['cmdOptions', "context"] = "Fastqc"
    @params['mail'] = ""
    @params['mail', "context"] = "Notifications"
    @params['ai_provider'] = ''
    @params['ai_provider', 'description'] = "AI mode (1/4): provider name. Example: 'custom' for FGCZ-hosted LLMs, 'openai', or 'anthropic'. ALL FOUR AI fields must be filled to trigger MultiQC's --ai-summary-full mode."
    @params['ai_provider', "context"] = "Fastqc AI"
    @params['ai_model'] = ''
    @params['ai_model', 'description'] = "AI mode (2/4): model identifier. Example: 'Qwen3.6-27B-FP8' for the FGCZ Qwen endpoint."
    @params['ai_model', "context"] = "Fastqc AI"
    @params['ai_custom_endpoint'] = ''
    @params['ai_custom_endpoint', 'description'] = "AI mode (3/4): chat completions endpoint URL. Example: 'http://fgcz-c-056:8081/v1/chat/completions'."
    @params['ai_custom_endpoint', "context"] = "Fastqc AI"
    @params['ai_custom_context_window'] = ''
    @params['ai_custom_context_window', 'description'] = "AI mode (4/4): context window in tokens. Example: '128000'."
    @params['ai_custom_context_window', "context"] = "Fastqc AI"
    @params['bake_section_summaries'] = false
    @params['bake_section_summaries', 'description'] = "OPT-IN: when checked AND all 4 AI fields above are filled, SUSHI replicates the per-section 'Summarize plot/table' AI calls from the MultiQC toolbox (one HTTP call per plot/table, ~30 s each, sequential). Responses are added as a 'Per-Section Summaries' tab in the AI Interpretation report. NOTE: this does NOT modify multiqc_report.html; the inline toolbox buttons there still require manual clicking."
    @params['bake_section_summaries', "context"] = "Fastqc AI"
    @params['extra_ai_call'] = false
    @params['extra_ai_call', 'description'] = "OPT-IN: when checked AND all 4 AI fields above are filled AND 'Extra AI prompt' below is non-empty, SUSHI makes one additional LLM call combining MultiQC's prompt with your extra instructions. The result is added as an 'FGCZ Follow-up' tab in the AI Interpretation report."
    @params['extra_ai_call', "context"] = "Fastqc AI"
    @params['extra_ai_prompt'] = ''
    @params['extra_ai_prompt', 'description'] = "Free-text prompt appended to MultiQC's own prompt for the FGCZ follow-up call. IGNORED unless 'Extra AI call' is checked above (SUSHI's UI cannot grey-out conditionally; treat this textbox as 'gray when checkbox off'). Example: 'Focus on per-base quality issues; flag any sample with >20% duplication; recommend re-runs.'"
    @params['extra_ai_prompt', "context"] = "Fastqc AI"
    @modules = ["QC/FastQC", "Dev/R", "Tools/Picard", "Tools/samtools", "Dev/Python",  "QC/fastp", "QC/MultiQC"]
    @inherit_columns = ["Order Id"]
  end
 def set_default_parameters
    @params['paired'] = dataset_has_column?('Read2')
  end
  def preprocess
    if @params['paired']
      @required_columns<<  'Read2'
    end
  end
  def next_dataset
    @params['name'] = 'FastQC'
    fastqc_file = File.join(@result_dir, @params['name'])
    multiqc_file = File.join(@result_dir, 'multi_FastQC')
    ai_mode = %w[ai_provider ai_model ai_custom_endpoint ai_custom_context_window].all? { |k| !@params[k].to_s.strip.empty? }
    if @params['showNativeReports']
      ds = {'Name'=>@params['name'],
        'MultiQC Report [Link]'=>File.join(multiqc_file, 'multiqc_report.html'), ## that's the default name generated by the multiqc tool
        'FastQC Report [Link]'=>File.join(fastqc_file, 'fastqc.html'),
        'MultiQC [File]'=>multiqc_file,
        'FastQC [File]'=>fastqc_file
      }
    else
      ds = {'Name'=>@params['name'],
        'MultiQC Report [Link]'=>File.join(multiqc_file, 'multiqc_report.html'),
        'MultiQC [File]'=>multiqc_file,
        'FastQC [File]'=>fastqc_file
      }
    end
    if ai_mode
      ds['AI Interpretation [Link]'] = File.join(multiqc_file, 'ai_interpretation.html')
    end
    ds.merge(extract_columns(colnames: @inherit_columns))
  end
  def commands
    run_RApp("EzAppFastqc")
  end
end

if __FILE__ == $0
  usecase = FastqcApp.new

  usecase.project = "p1001"
  usecase.user = "masa"

  # set user parameter
  # for GUI sushi
  #usecase.params['process_mode'].value = 'SAMPLE'
  #usecase.params['refBuild'] = 'TAIR10'
  #usecase.params['paired'] = true
  #usecase.params['cores'] = 2
  #usecase.params['node'] = 'fgcz-c-048'

  # also possible to load a parameterset csv file
  # mainly for CUI sushi
  usecase.parameterset_tsv_file = 'tophat_parameterset.tsv'
  #usecase.params['name'] = 'name'

  # set input dataset
  # mainly for CUI sushi
  usecase.dataset_tsv_file = 'tophat_dataset.tsv'

  # also possible to load a input dataset from Sushi DB
  #usecase.dataset_sushi_id = 1

  # run (submit to workflow_manager)
  usecase.run
  #usecase.test_run

end
