#!/usr/bin/env ruby
# encoding: utf-8
# 20121112 masa workflow manager client
Version = '20130531-100153'

require 'drb/drb' 
require File.join((File.expand_path('../../lib',__FILE__)), 'optparse_ex.rb')

opt = OptionParser.new do |o|
  o.banner = "Usage:\n #{File.basename(__FILE__)} [options]"
#  o.on(:user, 'sushi lover', '-u user', '--user', 'who submitted?')
  o.on(:project, nil, '-p project', '--project', 'project number')
  o.on(:server, 'druby://localhost:12345', '-d server', '--server', 'workflow manager URI (default: druby://localhost:12345)')
  o.parse!(ARGV)
end

with_result = false
uri = opt.server||'druby://localhost:12345'
project_number = opt.project
wfmrc = if File.exist?(".wfmrc")
          ".wfmrc"
        elsif File.exist?(File.expand_path("~/.wfmrc"))
          File.expand_path("~/.wfmrc")
        end
if wfmrc
  File.readlines(wfmrc).each do |line|
    if line =~ /server:\s*(druby.+)/
      uri = $1
    end
    if line =~ /project:\s*(\d+)/
      project_number = $1
    end
  end
end
workflow_manager = DRbObject.new_with_uri(uri)
puts workflow_manager.job_list(with_result, project_number)
