source 'https://rubygems.org'

gem 'rails', '4.2.6'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
gem 'devise'
if `hostname`.chomp =~ /fgcz-c-047/
gem 'devise_ldap_authenticatable', '>= 0.6.1.1', :path => '/srv/kenlab/shared_sib_sushi/Gems/devise_ldap_authenticatable'
else
gem 'devise_ldap_authenticatable'
end
gem 'hpricot'
gem 'ruby_parser'

# Options for FGCZ gems:
# A) gem 'fgcz', :bzr => 'bzr+ssh://fgcz-s-034.uzh.ch/usr/local/ngseq/repo/Gems/fgcz'
#    but bzr source doesn't exist! (only git)
# B) gem 'fgcz', :path => '/srv/SushiFabric/Gems/fgcz'
# C) source 'https://gems-fgcz.uzh.ch:8888'
#    gem 'fgcz'
gem 'savon'
if `hostname`.chomp =~ /fgcz-c-047/
gem 'fgcz', :path => '/srv/kenlab/shared_sib_sushi/Gems/fgcz'
end

group :test do
  gem "rspec"
  gem "rspec-rails"
  gem 'simplecov'
  gem 'simplecov-rcov'
end

gem 'workflow_manager'
gem 'sushi_fabric'
gem 'chartkick'
#gem 'mysql2'
gem 'mysql2'
#gem 'activerecord-mysql2-adapter'
gem 'yaml_db'
#gem 'jquery-turbolinks'
gem "jstree-rails-4"
gem 'therubyracer'
