#!/usr/bin/env ruby
# encoding: utf-8

require 'sushi_fabric'
require_relative 'global_variables'
include GlobalVariables

class FastqcTestApp <  SushiFabric::SushiApp
  def initialize
    super
    @name = 'FastqcTest'
    @params['process_mode'] = 'DATASET'
    @analysis_category = 'QC'
    @description =<<-EOS
A quality control tool for NGS reads<br/>
<a href='http://www.bioinformatics.babraham.ac.uk/projects/fastqc'/>Web-site with docu and a tutorial video</a>
EOS
    @required_columns = ['Name','Read1']
    @required_params = ['paired']
    @params['cores'] = [1, 1, 2, 4, 8]
    @params['ram'] = [15, 30, 62]
    @params['ram', 'description'] = "GB"
    @params['scratch'] = [10, 10, 50, 100]
    @params['scratch', 'description'] = "GB"
    @params['paired'] = false
    @params['showNativeReports'] = false
    @params['showNativeReports', 'description'] = "uses the multi qc summary as primary report; native reports are generated and can be downloaded"
    @params['specialOptions'] = ''
    @params['cmdOptions'] = ""
    @params['mail'] = "masaomi.hatakeyama@uzh.ch"
    @modules = ["QC/FastQC", "Dev/R", "Tools/Picard", "Tools/samtools", "Dev/Python",  "QC/fastp"]
    @inherit_columns = ["Order Id", "BFabric Info"]
    @params['grandchildName'] = ''
    @params['grandchildName', 'description'] = 'Override aggregated grandchild dataset name (leave empty for default)'
  end
 def set_default_parameters
    @params['paired'] = dataset_has_column?('Read2')
    # Set default for grandchildName to OrderNumber_SUSHIAppName_grandchild if possible
    if @params['grandchildName'].to_s.strip.empty?
      order_id = nil
      if @dataset_hash && @dataset_hash.first
        # Find a header that represents Order Id (tag-insensitive)
        order_header = @dataset_hash.first.keys.find { |k| k.gsub(/\[.+\]/,'').strip =~ /Order Id/ }
        if order_header
          # Take the first non-empty order id across rows
          order_id = @dataset_hash.map { |row| row[order_header] }.compact.find { |v| !v.to_s.strip.empty? }
        end
      end
      base_name = if order_id && !order_id.to_s.strip.empty?
                    "#{order_id}_#{@name}"
                  else
                    @name
                  end
      @params['grandchildName'] = "#{base_name}_grandchild"
    end
  end
  def preprocess
    if @params['paired']
      @required_columns<<  'Read2'
    end
  end
  def next_dataset
    @params['name'] = 'FastQC'
    fastqc_file = File.join(@result_dir, @params['name'])
    multiqc_file = File.join(@result_dir, 'multi_FastQC')
    if @params['showNativeReports']
      ds = {'Name'=>@params['name'],
        'MultiQC Report [Link]'=>File.join(multiqc_file, 'multiqc_report.html'), ## that's the default name generated by the multiqc tool
        'FastQC Report [Link]'=>File.join(fastqc_file, 'fastqc.html'),
        'MultiQC [File]'=>multiqc_file,
        'FastQC [File]'=>fastqc_file
      }
    else
      ds = {'Name'=>@params['name'],
        'MultiQC Report [Link]'=>File.join(multiqc_file, 'multiqc_report.html'),
        'MultiQC [File]'=>multiqc_file,
        'FastQC [File]'=>fastqc_file
      }
    end
    ds.merge(extract_columns(colnames: @inherit_columns))
  end
  def grandchild_datasets
    #@grandchild = true
    grandchild_dataset = []
    rows = @dataset.is_a?(Array) ? @dataset : []
    return grandchild_dataset if rows.empty?
    
    # Use @dataset instead of @dataset_hash to respect sample selection
    # In DATASET mode, @dataset contains only selected samples
    rows.each_with_index do |row, i|
      sample = Hash[*row.map{|key,value| [key.gsub(/\[.+\]/,'').strip, value]}.flatten]
      
      # Create per-sample grandchild dataset
      grandchild_dataset << {
        'Name' => "#{@params['name']}_#{sample['Name']}",
        'FastQC Report [Link]' => File.join(@result_dir, @params['name'], "#{sample['Name']}_fastqc.html"),
        'FastQC Data [File]' => File.join(@result_dir, @params['name'], "#{sample['Name']}_fastqc_data.txt"),
      }.merge(extract_columns(colnames: @inherit_columns || [], sample_name: sample['Name']))
      #}.merge(extract_columns(colnames: @inherit_columns || [], sample_name: sample['Name'], strict: true))
      #}.merge(extract_columns(colnames: @inherit_columns || []))
    end
    
    grandchild_dataset
  end
  def commands
    commands = ""
    
    # Create dummy outputs for each selected sample
    rows = @dataset.is_a?(Array) ? @dataset : []
    rows.each do |row|
      sample = Hash[*row.map{|key,value| [key.gsub(/\[.+\]/,'').strip, value]}.flatten]
      sample_name = sample['Name']
      
      commands << "mkdir -p #{@params['name']}\n"
      commands << "echo 'FastQC data for #{sample_name}' > #{@params['name']}/#{sample_name}_fastqc_data.txt\n"
      commands << "echo '<html><body>FastQC report for #{sample_name}</body></html>' > #{@params['name']}/#{sample_name}_fastqc.html\n"
    end
    
    if @params['showNativeReports']
      commands << "mkdir -p detailed_analysis\n"
      commands << "echo '<html><body>Dummy details</body></html>' > detailed_analysis/details.html\n"
    end
    
    commands << "\n"
    commands << run_RApp("EzAppFastqc")
    commands
  end
end

if __FILE__ == $0
  usecase = FastqcApp.new

  usecase.project = "p1001"
  usecase.user = "masa"

  # set user parameter
  # for GUI sushi
  #usecase.params['process_mode'].value = 'SAMPLE'
  #usecase.params['refBuild'] = 'TAIR10'
  #usecase.params['paired'] = true
  #usecase.params['cores'] = 2
  #usecase.params['node'] = 'fgcz-c-048'

  # also possible to load a parameterset csv file
  # mainly for CUI sushi
  usecase.parameterset_tsv_file = 'tophat_parameterset.tsv'
  #usecase.params['name'] = 'name'

  # set input dataset
  # mainly for CUI sushi
  usecase.dataset_tsv_file = 'tophat_dataset.tsv'

  # also possible to load a input dataset from Sushi DB
  #usecase.dataset_sushi_id = 1

  # run (submit to workflow_manager)
  usecase.run
  #usecase.test_run

end
